theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
title: Ivan Villa-Renteria
description: Ivan's Website
colors:
    gradient_left: "#ff0090"
    gradient_right: "#00bbff"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
